root_file_mc: "/Users/ginnocen/Desktop/MITHIGAnalysis2024/Skims/SkimsMC/20241216_v1_filelist20241216_Pthat2_ForceD0Decay100M_BeamA_v1/mergedfile.root"  # Replace with your ROOT file name
tree_name: "Tree"          # Replace with your TTree name
ptmin: 1
ptmax: 2
ymin: -1
ymax: +1
output_csv: output_pt_p1p2_y_m1p1.cvs
output_root: output_pt_p1p2_y_m1p1.root
output_model: XGBoostMConly_pt_p1p2_y_m1p1.json
output_csv: output_applied_XGBoostMConly_pt_p1p2_y_m1p1.csv
random_state: 42
